DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
	ID VARCHAR2(20) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(30) NOT NULL
);
INSERT INTO ACCOUNT VALUES('admin','1234','관리자');

DROP TABLE POST;
CREATE TABLE POST(
	PCODE NUMBER(6) NOT NULL PRIMARY KEY,
	PTYPE CHAR(4) NOT NULL,
	WRITER VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENTS VARCHAR2(1000),
	FOREIGN KEY (WRITER) REFERENCES ACCOUNT (ID)
);
DROP TABLE COMMENT;
CREATE TABLE COMMENT(
	CMCODE NUMBER(6) NOT NULL PRIMARY KEY,
	CPCODE NUMBER(6) NOT NULL,
	WRITER VARCHAR2(20),
	CONTENTS VARCHAR2(500),
	FOREIGN KEY (WRITER) REFERENCES ACCOUNT (ID),
	FOREIGN KEY (CPCODE) REFERENCES POST (PCODE)
);
DROP TABLE REPLY;
CREATE TABLE REPLY(
	RCODE NUMBER(6) NOT NULL PRIMARY KEY,
	RCMCODE NUMBER(6) NOT NULL,
	WRITER VARCHAR2(20),
	CONTENTS VARCHAR2(500),
	FOREIGN KEY (WRITER) REFERENCES ACCOUNT (ID),
	FOREIGN KEY (RCMCODE) REFERENCES COMMENT (CMCODE)
);