/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-07-11 00:31:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lunch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/view/../intro/aside.jsp", Long.valueOf(1657499016732L));
    _jspx_dependants.put("/view/../intro/header.jsp", Long.valueOf(1657498345414L));
    _jspx_dependants.put("/view/../intro/login.jsp", Long.valueOf(1657499461095L));
    _jspx_dependants.put("/view/../intro/logout.jsp", Long.valueOf(1657498345416L));
    _jspx_dependants.put("/view/../intro/footer.jsp", Long.valueOf(1657498345414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>분경 학생마당</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../intro/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"h-line\">\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"logo\">로고</div>\r\n");
      out.write("		<div class=\"nav\">\r\n");
      out.write("			<h2><a href=\"../intro/home.jsp\">홈</a></h2>\r\n");
      out.write("			<h2><a href=\"../view/lunch.jsp\">오늘의 급식</a></h2>\r\n");
      out.write("			<h2><a href=\"#none\">공지사항</a></h2>\r\n");
      out.write("			<h2><a href=\"#none\">인기글</a></h2>\r\n");
      out.write("			<h2><a href=\"#none\">자유게시판</a></h2>\r\n");
      out.write("			<h2><a href=\"#none\">Q&A</a></h2>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		<div class=\"con\">\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<iframe class=\"lunchFrame\" src=\"https://school.koreacharts.com/school/meals/B000023220/contents.html\"></iframe>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../intro/asideStyle.css\">\r\n");
      out.write("<script>\r\n");
      out.write("function modalOpen(){\r\n");
      out.write("	");
if(session.getAttribute("id")!=null){
      out.write("\r\n");
      out.write("	document.getElementById('writeModal').setAttribute(\"class\",\"active\");\r\n");
      out.write("	");
}else{
      out.write("\r\n");
      out.write("		alert(\"로그인이 필요한 메뉴입니다.\");\r\n");
      out.write("	");
}
      out.write("\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("function modalClose(){\r\n");
      out.write("	document.getElementById('writeModal').removeAttribute(\"class\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"aside\">\r\n");
      out.write("	");

		if (session.getAttribute("id") != null) {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("	function logout(){\r\n");
      out.write("		if(confirm(\"로그아웃 하시겠습니까?\")){\r\n");
      out.write("			location.href=\"../intro/logoutCtrl.jsp\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"logout\">\r\n");
      out.write("	<h3>님 환영합니다.</h3>\r\n");
      out.write("	<div class=\"account\">\r\n");
      out.write("		<div class=\"account-menu\">\r\n");
      out.write("		<h3>아이디</h3>\r\n");
      out.write("			<a href=\"#none\">내 글 보기</a>/<a href=\"#none\">회원정보 수정</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<button type=\"button\" onclick=\"logout()\">로그아웃</button>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		} else {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	function check(){\r\n");
      out.write("		if(document.getElementById(\"id\").value==\"\"){\r\n");
      out.write("			alert(\"아이디가 입력되지 않았습니다.\");\r\n");
      out.write("			document.getElementById(\"id\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(document.getElementById(\"pw\").value==\"\"){\r\n");
      out.write("			alert(\"비밀번호가 입력되지 않았습니다.\");\r\n");
      out.write("			document.getElementById(\"pw\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}	\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("	<h3>로그인</h3>\r\n");
      out.write("	<form action=\"../intro/loginCtrl.jsp\" method=\"post\" onsubmit=\"return check()\">\r\n");
      out.write("		<div class=\"loginInput\">\r\n");
      out.write("			<input type=\"text\" id=\"id\" name=\"id\" placeholder=\"아이디\"><br>\r\n");
      out.write("			<input type=\"password\" id=\"pw\" name=\"pw\" placeholder=\"비밀번호\"><br>\r\n");
      out.write("		</div>\r\n");
      out.write("		<button type=\"submit\">로그인</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	<div class=\"account-menu\">\r\n");
      out.write("		<a href=\"#none\">아이디</a>/<a href=\"#none\">비밀번호 찾기</a>\r\n");
      out.write("		<a href=\"#none\" id=\"register\">회원가입</a>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		}
	
      out.write("\r\n");
      out.write("	<a href=\"#none\">\r\n");
      out.write("		<div class=\"write\" onclick=\"modalOpen()\">\r\n");
      out.write("			<h1>글 작성하기</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	</a>\r\n");
      out.write("	<div class=\"schedule\">\r\n");
      out.write("		<iframe src=\"http://xn--s39aj90b0nb2xw6xh.kr/\"></iframe>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"writeModal\">\r\n");
      out.write("	<div class=\"modalContents\">\r\n");
      out.write("		<h2>카테고리 선택</h2>\r\n");
      out.write("		<div class=\"modalBtn\">\r\n");
      out.write("		<button type=\"button\" onclick=\"location.href='../view/addPost.jsp?pType=NEWS'\">공지사항</button>\r\n");
      out.write("		<button type=\"button\" onclick=\"location.href='../view/addPost.jsp?pType=FREE'\">자유게시판</button>\r\n");
      out.write("		<button type=\"button\" onclick=\"location.href='../view/addPost.jsp?pType=QUES'\">Q&A</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"close-writeModal\" onclick=\"modalClose()\">X 닫기</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div class=\"f-line\">\r\n");
      out.write("	<footer> </footer>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
